##### Terminal / Color #########################################################

set -g default-terminal "tmux-256color"

set -as terminal-overrides ",wezterm*:Tc"
set -as terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 10

##### Windows #################################################################

set -g renumber-windows on

##### Pane ####################################################################

set -g mouse on

##### Status ##################################################################

set -g status-interval 5
set -g status-position bottom

##### Copy Mode ###############################################################

setw -g mode-keys vi
